name: Test Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "21.4.0"
      - name: Install dependencies
        run: npm install
      - name: Run finished actions
        run: echo "Finished!! Depencencies installed successfully!!"
